[workspace]
members = [
    "crates/zkbind-cli",
    "crates/zkbind-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
authors = ["Volodymyr Stetsenko"]
license = "Apache-2.0"
repository = "https://github.com/VolodymyrStetsenko/ZkBind"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
